### ISSUE TITLE
Log-Average Miss Rate Implementation of evaluation indicators

### ISSUE THREAD

**Issue by 3232731490** [yuanmaoxun/C2Former#13]
Hello, can you provide evaluation functions for KAIST data sets? There does not seem to be a default implementation of MR Metrics in mmdet

**Comment by yuanmaoxun** [comment]
You can evaluate the KAIST datasets through (https://github.com/CalayZhou/MBNet/tree/master/KAISTdevkit-matlab-wrapper).
