### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by 9796l** [yuanmaoxun/C2Former#5]

**Comment by zjj421** [comment]
+1，方便告诉下具体的依赖包的版本吗，比如mmdet、mmcv、cuda版本，直接pip install -r requirements.txt后运行会报各种各样的mmdet、mmcv版本不适配的错误。

**Comment by qiherong** [comment]
同问你配置好了吗？

**Comment by yuanmaoxun** [comment]
Refer to [mmrotate](https://mmrotate.readthedocs.io/en/latest/install.html) environment configuration.
