### ISSUE TITLE
Why are the results of MBNet significantly worse than those reported in its original paper?

### ISSUE THREAD

**Issue by XueZ-phd** [yuanmaoxun/C2Former#7]
Hello Author,

This is an interesting work.

I am curious why the results in Table V are much worse than those reported in their original paper.

**Comment by qiherong** [comment]
![image](https://github.com/user-attachments/assets/88960271-4f13-431b-a1ff-fac4017dbcca)
in Table v the results of the "all day night" in MB papers is 8% ,

**Comment by yuanmaoxun** [comment]
@qiherong We evaluate the results in "All" setting rather than "Resonable" setting.

**Comment by qiherong** [comment]
I still don't understand your meaning, could you please explain it in detail?

**Comment by yuanmaoxun** [comment]
@qiherong You can refer to this [article ](https://arxiv.org/abs/2008.08418).
